### ISSUE TITLE
Add reviews on product

### ISSUE THREAD

**Issue by syko240** [Elock98/D0018E-Project#40]
rating: 1-5 
review: comment

**Comment by Elock98** [comment]
- [ ] User can set score
- [ ] User can leave review

**Comment by Elock98** [comment]
Should only be able to review after purchase.

**Comment by Elock98** [comment]
Needs fixing:

- [ ] Change "score" to "rating" in insert query
- [ ] Comment needs to be surrounded by " ' " in the insert query
